#! python3
# https://www.reddit.com/r/dailyprogrammer/comments/271xyp/622014_challenge_165_easy_ascii_game_of_life/
from copy import deepcopy


def solve(n, w, h, grid):
    ngrid = [list(i) for i in grid.splitlines()]
    for _ in range(n):
        grid = deepcopy(ngrid)
        for y in range(h):
            for x in range(w):
                neighbours = sum(1 for i in ((y - 1) % h, y, (y + 1) % h)
                                 for j in ((x - 1) % w, x, (x + 1) % w)
                                 if (i, j) != (y, x) and grid[i][j] == "#")
                if neighbours == 3:
                    ngrid[y][x] = "#"
                elif not 2 <= neighbours < 3:
                    ngrid[y][x] = "."
    [print("".join(i)) for i in ngrid]


solve(7, 10, 10, """..........
..........
..#.......
...#......
.###......
..........
..........
..........
..........
..........""")

solve(32, 17, 17, """.................
.................
....###...###....
.................
..#....#.#....#..
..#....#.#....#..
..#....#.#....#..
....###...###....
.................
....###...###....
..#....#.#....#..
..#....#.#....#..
..#....#.#....#..
.................
....###...###....
.................
.................""")
